const KEY="job_description_library_v1";
const seed=[
{id:"1",name:"مدير الموارد البشرية",dept:"الموارد البشرية",manager:"المدير العام",date:"2026-09-21",purpose:"إدارة وتنظيم أعمال الموارد البشرية بما يضمن تطبيق السياسات والإجراءات ورفع كفاءة القوى العاملة.",responsibilities:["الإشراف على عمليات الموارد البشرية والملفات الوظيفية.","متابعة الحضور والانصراف والإجازات والجزاءات.","إعداد التقارير الدورية ورفع التوصيات للإدارة.","متابعة الالتزام بالأنظمة واللوائح الداخلية.","تنسيق احتياجات الإدارات من القوى العاملة."],routine:["مراجعة الحضور والملاحظات.","متابعة الطلبات والمعاملات المفتوحة.","التنسيق مع مديري الإدارات.","تحديث سجلات الموظفين."],authorities:["متابعة تطبيق سياسات الموارد البشرية.","طلب المستندات والبيانات اللازمة من الإدارات.","رفع التوصيات الإدارية المتعلقة بالموظفين."],qualifications:["بكالوريوس في الموارد البشرية أو إدارة الأعمال أو تخصص ذي صلة."],skills:["التنظيم وإدارة الملفات.","التواصل وإعداد التقارير.","إجادة الأنظمة المكتبية."],kpi:["دقة واكتمال ملفات الموظفين.","سرعة إنجاز معاملات الموارد البشرية.","نسبة الالتزام بإجراءات الحضور والإجازات.","دقة التقارير الدورية."],compliance:["السرية والمحافظة على بيانات الموظفين.","الالتزام باللوائح الداخلية والتعليمات الإدارية."]},
{id:"2",name:"أخصائي موارد بشرية",dept:"الموارد البشرية",manager:"مدير الموارد البشرية",date:"2026-09-21",purpose:"تنفيذ معاملات الموارد البشرية اليومية والمحافظة على دقة بيانات وسجلات الموظفين.",responsibilities:["تحديث ملفات الموظفين وبياناتهم.","متابعة الإجازات والمباشرات والخطابات.","إعداد ومراجعة كشوف الحضور والانصراف.","تنفيذ المعاملات الإدارية المتعلقة بالموظفين.","حفظ المستندات وترتيب الأرشيف."],routine:["مراجعة الطلبات الواردة.","تحديث قواعد البيانات.","متابعة النواقص في ملفات الموظفين."],authorities:["طلب المستندات الناقصة وفق الإجراءات.","متابعة المعاملات مع الإدارات المعنية."],qualifications:["بكالوريوس أو دبلوم في الموارد البشرية أو الإدارة."],skills:["الدقة وسرعة الإنجاز.","Excel والأنظمة المكتبية.","التواصل والمتابعة."],kpi:["نسبة اكتمال الملفات.","دقة البيانات.","زمن إنجاز المعاملات."],compliance:["الحفاظ على سرية البيانات.","الالتزام بساعات الدوام والإجراءات."]},
{id:"3",name:"مهندس مكتب فني",dept:"المكتب الفني",manager:"مدير المكتب الفني",date:"2026-09-21",purpose:"تنفيذ أعمال المكتب الفني ودعم المشاريع من خلال إعداد ومراجعة المستندات الفنية والكميات والمخططات.",responsibilities:["مراجعة المخططات والمواصفات الفنية.","إعداد ومراجعة حصر الكميات.","إعداد ومراجعة المستخلصات والمطالبات الفنية حسب نطاق العمل.","التنسيق الفني مع المشاريع والاستشاريين.","إعداد ومراجعة المخططات التنفيذية وطلبات المعلومات."],routine:["متابعة المستندات الفنية المفتوحة.","تحديث جداول الكميات.","التنسيق مع مهندسي المواقع."],authorities:["طلب البيانات الفنية من فرق المشاريع.","إبداء الملاحظات الفنية ضمن نطاق الصلاحيات.","رفع المستندات للاعتماد حسب التسلسل الإداري."],qualifications:["بكالوريوس هندسة في التخصص المناسب."],skills:["قراءة المخططات.","AutoCAD وExcel والبرامج الفنية ذات الصلة.","التنظيم والدقة."],kpi:["دقة المستندات والكميات.","الالتزام بمواعيد التسليم.","نسبة إغلاق الملاحظات الفنية."],compliance:["الالتزام بإجراءات اعتماد المستندات.","عدم إصدار أي مستند خارج الصلاحيات المعتمدة."]},
{id:"4",name:"مهندس موقع",dept:"إدارة المشاريع",manager:"مدير المشروع",date:"2026-09-21",purpose:"الإشراف على تنفيذ الأعمال بالموقع وفق المخططات والمواصفات والبرنامج الزمني.",responsibilities:["متابعة تنفيذ الأعمال بالموقع.","التنسيق مع المقاولين والفرق الفنية.","متابعة الجودة والكميات والبرنامج الزمني.","رفع تقارير الإنجاز والملاحظات.","التأكد من تطبيق متطلبات السلامة."],routine:["جولة الموقع.","مراجعة خطة العمل اليومية.","توثيق نسب الإنجاز والملاحظات."],authorities:["توجيه فرق التنفيذ ضمن نطاق العمل.","رفع طلبات المواد والمعدات وفق الإجراءات."],qualifications:["بكالوريوس هندسة وتخصص مناسب للمشروع."],skills:["قراءة المخططات وإدارة الموقع.","التخطيط والمتابعة.","التواصل وحل المشكلات."],kpi:["نسبة الإنجاز مقابل الخطة.","جودة الأعمال.","إغلاق الملاحظات في المواعيد."],compliance:["معدات الوقاية ومتطلبات السلامة.","الالتزام بتعليمات المشروع وسلسلة الاعتماد."]},
{id:"5",name:"محاسب",dept:"الإدارة المالية والمحاسبة",manager:"المدير المالي",date:"2026-09-21",purpose:"تنفيذ العمليات المحاسبية اليومية وإعداد السجلات والتقارير المالية بدقة.",responsibilities:["تسجيل القيود والعمليات المحاسبية.","مراجعة المستندات المؤيدة للصرف والتحصيل.","مطابقة الحسابات وكشوف البنوك.","إعداد التقارير والكشوف المطلوبة.","حفظ المستندات المالية."],routine:["مراجعة القيود.","مطابقة الأرصدة.","متابعة المستندات الناقصة."],authorities:["طلب المستندات المؤيدة للعمليات.","إعداد المسودات المحاسبية ضمن الصلاحيات."],qualifications:["بكالوريوس محاسبة أو تخصص ذي صلة."],skills:["Excel والأنظمة المحاسبية.","الدقة والتحليل.","إدارة الوقت."],kpi:["دقة القيود.","نسبة المطابقات المكتملة.","الالتزام بالمواعيد المالية."],compliance:["سرية المعلومات المالية.","عدم اعتماد أو صرف أي عملية خارج الصلاحيات."]},
{id:"6",name:"مسؤول المشتريات",dept:"المشتريات",manager:"مدير المشتريات",date:"2026-09-21",purpose:"تنظيم وتنفيذ عمليات الشراء والتنسيق مع الموردين بما يحقق احتياجات العمل وفق الإجراءات المعتمدة.",responsibilities:["استلام ومراجعة طلبات الشراء.","طلب عروض الأسعار ومقارنتها.","التنسيق مع الموردين ومتابعة التوريد.","حفظ عروض الأسعار وأوامر الشراء.","متابعة المواعيد والكميات."],routine:["متابعة أوامر الشراء المفتوحة.","تحديث حالة التوريدات.","التنسيق مع المستودعات والمشاريع."],authorities:["التواصل مع الموردين ضمن الصلاحيات.","طلب عروض الأسعار والمعلومات الفنية."],qualifications:["مؤهل مناسب وخبرة في المشتريات."],skills:["التفاوض والمتابعة.","Excel وإدارة المستندات.","التنظيم."],kpi:["زمن دورة الشراء.","نسبة التوريد في الموعد.","اكتمال مستندات الشراء."],compliance:["الالتزام بمصفوفة الصلاحيات.","تجنب تضارب المصالح والمحافظة على سرية الأسعار."]},
{id:"7",name:"مسؤول الجودة",dept:"الجودة",manager:"مدير الجودة",date:"2026-09-21",purpose:"متابعة تطبيق متطلبات الجودة وتوثيق الفحوصات والملاحظات في المشاريع.",responsibilities:["متابعة خطط الجودة وإجراءات الفحص.","مراجعة نتائج الاختبارات والتقارير.","تسجيل الملاحظات ومتابعة إغلاقها.","التنسيق مع فرق التنفيذ والاستشاري.","حفظ سجلات الجودة."],routine:["جولات الفحص.","مراجعة طلبات الفحص.","تحديث سجل الملاحظات."],authorities:["طلب معالجة حالات عدم المطابقة.","إيقاف الإجراء المخالف ضمن الصلاحيات ورفع الحالة للمسؤول."],qualifications:["بكالوريوس هندسة أو تخصص مناسب للجودة."],skills:["التدقيق والتوثيق.","قراءة المواصفات.","إعداد التقارير."],kpi:["نسبة إغلاق الملاحظات.","اكتمال سجلات الجودة.","معدل حالات عدم المطابقة."],compliance:["الالتزام بخطط الجودة والمواصفات المعتمدة.","عدم اعتماد نتائج غير موثقة."]},
{id:"8",name:"مسؤول السلامة والصحة المهنية",dept:"السلامة والصحة المهنية",manager:"مدير السلامة",date:"2026-09-21",purpose:"متابعة تطبيق متطلبات السلامة والحد من المخاطر داخل المواقع ومرافق الشركة.",responsibilities:["تنفيذ جولات السلامة.","رصد المخاطر والمخالفات.","متابعة معدات الوقاية.","التوعية والتعليمات اليومية.","إعداد تقارير الحوادث والملاحظات."],routine:["تفقد الموقع.","متابعة إغلاق الملاحظات.","تسجيل حالات عدم الالتزام."],authorities:["إيقاف العمل الخطر ضمن الصلاحيات.","رفع المخالفات والتوصيات للإدارة."],qualifications:["مؤهل مناسب وشهادات مهنية ذات صلة."],skills:["تقييم المخاطر.","التواصل والتوعية.","إعداد التقارير."],kpi:["عدد الملاحظات المغلقة.","نسبة الالتزام بمتطلبات الوقاية.","زمن الاستجابة للمخاطر."],compliance:["الالتزام بتعليمات السلامة.","استخدام معدات الوقاية والمحافظة عليها."]},
{id:"9",name:"أمين مستودع",dept:"المستودعات",manager:"مدير المستودعات",date:"2026-09-21",purpose:"إدارة حركة المواد والمخزون واستلام وصرف المواد وفق المستندات والإجراءات المعتمدة.",responsibilities:["استلام المواد وفحص المستندات.","تسجيل الإدخالات والإخراجات.","صرف المواد وفق الطلبات المعتمدة.","متابعة أرصدة المخزون.","تنظيم وترتيب المستودع."],routine:["مطابقة الرصيد.","ترتيب المواد.","متابعة المواد الراكدة أو الناقصة."],authorities:["رفض الاستلام غير المطابق ورفع الحالة.","طلب المستندات اللازمة للصرف."],qualifications:["مؤهل مناسب وخبرة في المستودعات."],skills:["الجرد والتنظيم.","استخدام أنظمة المخزون.","الدقة."],kpi:["دقة المخزون.","نسبة الفروقات في الجرد.","سرعة تجهيز طلبات الصرف."],compliance:["عدم صرف أي مادة دون مستند معتمد.","المحافظة على عهدة المستودع."]},
{id:"10",name:"مسؤول الحركة",dept:"الحركة والنقل",manager:"مدير الإدارة الإدارية",date:"2026-09-21",purpose:"تنظيم حركة المركبات والسائقين والمعدات ومتابعة الاستخدام وفق التعليمات والإجراءات.",responsibilities:["تنظيم جداول المركبات والسائقين.","متابعة صلاحيات المركبات والسائقين.","توثيق تسليم واستلام المركبات.","متابعة الصيانة والأعطال.","رفع تقارير المخالفات والحوادث."],routine:["مراجعة حركة المركبات.","متابعة الطلبات والتكليفات.","تحديث سجلات المركبات والسائقين."],authorities:["تنظيم حركة المركبات ضمن التعليمات.","رفع حالات المخالفة أو الاستخدام غير المصرح به."],qualifications:["مؤهل مناسب وخبرة في الحركة أو الأسطول."],skills:["التنظيم والمتابعة.","إدارة السجلات.","التواصل."],kpi:["نسبة جاهزية المركبات.","دقة سجلات الحركة.","زمن معالجة طلبات الحركة."],compliance:["عدم تسليم مركبة أو تكليف سائق خارج الإجراءات المعتمدة.","الالتزام بالتعليمات المرورية وتعليمات الشركة."]}
];
let jobs=load(),activeDept="الكل",currentId=null;
const $=s=>document.querySelector(s);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:seed}catch{return seed}}
function save(){localStorage.setItem(KEY,JSON.stringify(jobs));render()}
function lines(v){return(v||"").split("\n").map(x=>x.trim()).filter(Boolean)}
function departments(){return[...new Set(jobs.map(j=>j.dept).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ar"))}
function renderDepts(){const ds=departments();$("#deptCount").textContent=ds.length;$("#jobCount").textContent=jobs.length;$("#departments").innerHTML=ds.map(d=>'<button class="dept '+(activeDept===d?"active":"")+'" data-dept="'+esc(d)+'"><span>'+esc(d)+'</span><b>'+jobs.filter(j=>j.dept===d).length+'</b></button>').join("");$("#allDeptBtn").classList.toggle("active",activeDept==="الكل");$("#deptList").innerHTML=ds.map(d=>'<option value="'+esc(d)+'"></option>').join("")}
function render(){renderDepts();const q=$("#search").value.trim().toLowerCase();let list=jobs.filter(j=>(activeDept==="الكل"||j.dept===activeDept)&&[j.name,j.dept,j.manager,j.purpose].join(" ").toLowerCase().includes(q));list.sort((a,b)=>$("#sort").value==="dept"?a.dept.localeCompare(b.dept,"ar")||a.name.localeCompare(b.name,"ar"):a.name.localeCompare(b.name,"ar"));$("#jobs").innerHTML=list.map(card).join("");$("#empty").classList.toggle("hidden",list.length>0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function card(j){return'<article class="job-card"><span class="tag">'+esc(j.dept)+'</span><h3>'+esc(j.name)+'</h3><div class="manager">الرئيس المباشر: '+esc(j.manager||"—")+'</div><p class="purpose">'+esc(j.purpose||"لا يوجد وصف مختصر.")+'</p><div class="card-bottom"><button class="open" data-open="'+j.id+'">فتح الوصف</button><button class="edit-link" data-edit="'+j.id+'">تعديل</button></div></article>'}
function section(title,value,full=false){const ls=Array.isArray(value)?value:lines(value);return'<div class="section '+(full?"full":"")+'"><h3>'+title+'</h3>'+(ls.length?'<ul>'+ls.map(x=>'<li>'+esc(x)+'</li>').join("")+'</ul>':'<p>لا توجد بيانات مضافة.</p>')+'</div>'}
function showDetail(id){const j=jobs.find(x=>x.id===id);if(!j)return;currentId=id;$("#detail").innerHTML='<div class="detail-top"><span class="tag">'+esc(j.dept)+'</span><h2>'+esc(j.name)+'</h2><p>الرئيس المباشر: '+esc(j.manager||"—")+' • آخر تحديث: '+esc(j.date||"—")+'</p><div class="detail-actions"><button class="btn gold" onclick="window.print()">طباعة / حفظ PDF</button><button class="btn ghost" style="color:var(--navy)" onclick="editJob(currentId)">تعديل</button><button class="btn ghost" style="color:var(--danger)" onclick="deleteJob(currentId)">حذف</button></div></div><div class="detail-grid"><div class="section full"><h3>الهدف العام من الوظيفة</h3><p>'+esc(j.purpose||"لا يوجد")+'</p></div>'+section("المهام والمسؤوليات الرئيسية",j.responsibilities,true)+section("المهام اليومية / الدورية",j.routine)+section("الصلاحيات والمسؤوليات",j.authorities)+section("المؤهلات",j.qualifications)+section("الخبرات والمهارات",j.skills)+section("مؤشرات الأداء KPI",j.kpi)+section("متطلبات الالتزام والانضباط",j.compliance,true)+'</div>';$("#detailModal").classList.remove("hidden")}
function editJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$("#jobId").value=j.id;$("#fName").value=j.name;$("#fDept").value=j.dept;$("#fManager").value=j.manager||"";$("#fDate").value=j.date||"";$("#fPurpose").value=j.purpose||"";$("#fResponsibilities").value=(j.responsibilities||[]).join("\n");$("#fRoutine").value=(j.routine||[]).join("\n");$("#fAuthorities").value=(j.authorities||[]).join("\n");$("#fQualifications").value=(j.qualifications||[]).join("\n");$("#fSkills").value=(j.skills||[]).join("\n");$("#fKpi").value=(j.kpi||[]).join("\n");$("#fCompliance").value=(j.compliance||[]).join("\n");$("#formTitle").textContent="تعديل الوصف الوظيفي";$("#detailModal").classList.add("hidden");$("#formModal").classList.remove("hidden")}
function deleteJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;if(confirm("هل أنت متأكد من حذف وصف وظيفة «"+j.name+"»؟")){jobs=jobs.filter(x=>x.id!==id);save();$("#detailModal").classList.add("hidden")}}
function addJob(){$("#jobForm").reset();$("#jobId").value="";$("#fDate").value=new Date().toISOString().slice(0,10);$("#formTitle").textContent="إضافة وصف وظيفي";$("#formModal").classList.remove("hidden")}
document.addEventListener("click",e=>{const d=e.target.closest("[data-dept]");if(d){activeDept=d.dataset.dept;render();return}if(e.target.id==="allDeptBtn"){activeDept="الكل";render();return}const o=e.target.closest("[data-open]");if(o)showDetail(o.dataset.open);const ed=e.target.closest("[data-edit]");if(ed)editJob(ed.dataset.edit);if(e.target.dataset.close)$(e.target.dataset.close).classList.add("hidden")});
$("#search").addEventListener("input",render);$("#sort").addEventListener("change",render);$("#addBtn").addEventListener("click",addJob);
$("#jobForm").addEventListener("submit",e=>{e.preventDefault();const id=$("#jobId").value||crypto.randomUUID();const obj={id,name:$("#fName").value.trim(),dept:$("#fDept").value.trim(),manager:$("#fManager").value.trim(),date:$("#fDate").value,purpose:$("#fPurpose").value.trim(),responsibilities:lines($("#fResponsibilities").value),routine:lines($("#fRoutine").value),authorities:lines($("#fAuthorities").value),qualifications:lines($("#fQualifications").value),skills:lines($("#fSkills").value),kpi:lines($("#fKpi").value),compliance:lines($("#fCompliance").value)};const idx=jobs.findIndex(x=>x.id===id);if(idx>=0)jobs[idx]=obj;else jobs.push(obj);save();$("#formModal").classList.add("hidden")});
$("#exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(jobs,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="job-description-library.json";a.click();URL.revokeObjectURL(a.href)});
$("#importInput").addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;jobs=x;save();alert("تم استيراد البيانات بنجاح.")}catch{alert("ملف البيانات غير صالح.")}};r.readAsText(file)});
window.editJob=editJob;window.deleteJob=deleteJob;window.currentId=null;render();